name: digilead
channels:
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - scipy
  - pandas
  - scikit-learn
  - ipykernel
  - ipywidgets
  - keras
  - tensorflow
  - pip:
    - bruges
    - welly
